-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe
SELECT * FROM SIGHTS;
CREATE TABLE SIGHTS (
        TITLE VARCHAR2(400) NOT NULL PRIMARY KEY,
        SEQ NUMBER(10) NOT NULL ,
        CATEGORY NUMBER(10) NOT NULL,
        THEME VARCHAR2(400) NOT NULL,
        FILENAME VARCHAR2(4000),
        ADDRESS VARCHAR2(400) ,
        PHONE VARCHAR2(400) ,
        HOMEPAGE VARCHAR2(400) ,
        CONTENT VARCHAR2(4000) ,
        ADDSCHEDULE NUMBER(20),
        DEL NUMBER(20),
        READCOUNT NUMBER(20),
        LIKECOUNT NUMBER(20)
);
--DROP TABLE SIGHTS CASCADE CONSTRAINTS;
--관광지이름, 관광지고유번호, 관광지종류, 관광지테마, 사진파일경로, 관광지주소, 관광지전화, 관광지홈페이지, 관광지설명, 일정추가횟수, 삭제여부, 조회수
CREATE SEQUENCE SEQ_SIGHTS START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;

SELECT * FROM SIGHTS WHERE CATEGORY= 2 AND SEQ>=0 AND SEQ<=5 ;

 SELECT TITLE, SEQ, CATEGORY, THEME
 FROM (SELECT ROW_NUMBER()OVER(ORDER BY SEQ ASC) AS RNUM
 ,TITLE, SEQ, CATEGORY, THEME FROM SIGHTS  WHERE CATEGORY= 0 )	
WHERE RNUM >= 10  AND RNUM <= 20  


SELECT SEQ, TITLE, THEME, ADDRESS FROM 
				 (SELECT ROW_NUMBER()OVER(ORDER BY SEQ ASC) AS RNUM ,
				 SEQ, TITLE,  THEME, ADDRESS FROM SIGHTS WHERE CATEGORY= 1)
				 WHERE RNUM >= 1  AND RNUM <= 5 
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME) VALUES('테스트타이틀', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마');
SELECT TITLE,SEQ,ADDSCHEDULE FROM SIGHTS  WHERE ADDSCHEDULE IS NOT NULL ORDER BY ADDSCHEDULE DESC;

--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('노리매공원', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',4);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('새연교', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',8);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('보롬왓', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',10);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('김녕해수욕장', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',0);
--
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('노리', SEQ_SIGHTS.NEXTVAL, 0, 'nature',1);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('새연교공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',40);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('김녕해수욕', SEQ_SIGHTS.NEXTVAL, 0, 'nature',45);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('천지연폭포공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',42);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('폭포공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',2);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('제주바다', SEQ_SIGHTS.NEXTVAL, 0, 'nature',8);






