-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE SIGHT_REVIEW (
	SEQ NUMBER NOT NULL PRIMARY KEY,
	TITLE VARCHAR2(400) NOT NULL,	
	ID VARCHAR2(400) NOT NULL,
	CONENT VARCHAR2(4000),
	SCORE NUMBER(4)
);
--DROP TABLE SIGHT_REVIEW CASCADE CONSTRAINTS;
--

CREATE SEQUENCE SEQ_SIGHT_REVIEW START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;
--DROP SEQUENCE SEQ_SIGHT_REVIEW;

SELECT * FROM SIGHT_REVIEW;

--INSERT INTO SIGHT_REVIEW VALUES( SEQ_SIGHT_REVIEW.NEXTVAL, '테스트 제목', 'admin', '테스트 내용', 3); 
