-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE DETAIL_SCHEDULES (
	SEQ NUMBER NOT NULL PRIMARY KEY,
	PARENT_SEQ NUMBER NOT NULL ,
	STIME VARCHAR2(400) ,
	DEST VARCHAR2(400)
);
--여행상세 번호, 여행일정코드(SCHEDULES 테이블), 일정시작시간, 여행목적지
--DROM TABLE DETAIL_SCHEDULES;

CREATE SEQUENCE SEQ_DETAIL_SCHEDULES START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;
--DROP SEQUENCE SEQ_DETAIL_SCHEDULES ;

SELECT * FROM DETAIL_SCHEDULES;

--INSERT INTO DETAIL_SCHEDULES VALUES( SEQ_DETAIL_SCHEDULES.NEXTVAL, 1, '09:00', '우도');