-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE SCHEDULES (
	SEQ NUMBER NOT NULL PRIMARY KEY,
	ID VARCHAR2(400) NOT NULL,
	TITLE VARCHAR2(400) NOT NULL,
	SDATE VARCHAR2(400) ,
	EDATE VARCHAR2(400) ,
	WDATE DATE
);
--DROP TABLE SCHEDULES CASCADE CONSTRAINTS;
--여행일정번호, 작성자, 일정제목, 일정시작일, 일정종료일, 작성일

CREATE SEQUENCE SEQ_SCHEDULES START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;

SELECT * FROM SCHEDULES;

--INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );

INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'aaa', '우', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
